/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Proyecto;

import javafx.application.Application;
import static javafx.application.Application.launch;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.stage.Stage;

/**
 *
 * @author Molina
 */
public class Main extends Application {

    @Override
    public void start(Stage stage) throws Exception {
        

        
        Parent root = FXMLLoader.load(getClass().getResource("/Vista/vistaLogin.fxml"));

        Scene scene = new Scene(root);
         //Cargar el archivo CSS
        
        scene.getStylesheets().add(getClass().getResource("/Styles/style.css").toExternalForm());
        
        stage.setScene(scene);
        stage.setTitle("Sportify");
        stage.getIcons().add(new Image("/Imagenes/Miscelanea/tenis.png"));
        stage.setResizable(false);
        stage.show(); 
        
        
    }

    public static void main(String[] args) {
        launch(args);
    }
}
